# Generated by Django 3.1.1 on 2020-09-20 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('real_name', models.CharField(max_length=100, unique=True)),
                ('tz', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_logout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='start_end_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('real_name', models.CharField(max_length=100, unique=True)),
                ('tz', models.CharField(max_length=100)),
                ('activity_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.start_end_time')),
            ],
        ),
    ]
